#!/usr/bin/env tsx
/**
 * Phase 6 PR 6.14 — typed `t` accessor generator.
 *
 * Reads `locales/en.json` (the source-of-truth dictionary per
 * `DEFAULT_LOCALE`) and emits a `.d.ts` file declaring deep nested
 * accessor types for the runtime `t` object exposed by
 * `src/lib/i18n.ts`. Top-level keys starting with `_` (i.e. `_meta.*`
 * metadata) are excluded — `t._meta` fails type-checking, matching the
 * runtime filter from PR 6.1 (`stripInternalKeys`).
 *
 * This is build-time only. PR 6.14 plan §23.5 constraint: the generator
 * MUST adapt to the existing runtime surface, not the reverse. No
 * call-site rewrites; no namespace renames; no buildTranslations
 * semantic changes.
 *
 * The emitted file is NOT wired into `src/lib/i18n.ts` automatically —
 * existing call sites use the inferred type from `buildTranslations`'s
 * return. The .d.ts is generated as documentation + future opt-in
 * tooling; call sites can add `import type { TStructure } from "./i18n.generated";`
 * if they want stricter typing.
 *
 * Invoked manually: `pnpm tsx scripts/i18n/generate-types.ts`.
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

type DictNode = string | { [key: string]: DictNode };

function isInternalKey(key: string): boolean {
  return key.startsWith("_");
}

function emitNode(node: DictNode, indent: number): string {
  if (typeof node === "string") {
    return "string";
  }
  const pad = "  ".repeat(indent);
  const innerPad = "  ".repeat(indent + 1);
  const entries = Object.entries(node).filter(([k]) => !isInternalKey(k));
  if (entries.length === 0) return "{}";
  const lines = entries.map(([k, v]) => {
    const safeKey = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
    return `${innerPad}${safeKey}: ${emitNode(v, indent + 1)};`;
  });
  return `{\n${lines.join("\n")}\n${pad}}`;
}

function main(): void {
  const enPath = resolve(process.cwd(), "locales", "en.json");
  const raw = readFileSync(enPath, "utf-8");
  const enDict = JSON.parse(raw) as Record<string, DictNode>;

  const banner = `// Auto-generated by scripts/i18n/generate-types.ts — do not edit by hand.\n// Mirrors locales/en.json (the DEFAULT_LOCALE fallback dict).\n// Top-level _-prefixed metadata keys (e.g. _meta) are excluded per\n// Phase 6 §5 invariant 13 — they are never exposed via the runtime\n// \`t\` accessor (stripInternalKeys in src/lib/i18n.ts).\n\n`;

  const structure = emitNode(enDict, 0);
  const output = `${banner}export interface TStructure ${structure}\n`;

  const outPath = resolve(process.cwd(), "src", "lib", "i18n.generated.d.ts");
  writeFileSync(outPath, output, "utf-8");
  console.log(`✓ Wrote ${outPath}`);
}

const url = import.meta.url;
if (typeof process !== "undefined" && url.endsWith(process.argv[1] ?? "")) {
  main();
}
