/**
 * TanStack Query key registry (G4 audit baseline).
 *
 * Do not import from application code — this file exists for architecture drift detection only.
 * Regenerate after intentional new keys: pnpm query-keys:audit -- --write-registry
 *
 * @see scripts/architecture/collect-query-keys.mjs
 * @see docs/architecture/architecture-hardening-addendum.md §9.4
 */
export const QUERY_KEY_REGISTRY_VERSION = 1 as const;

/**
 * Normalized query key shapes (JSON array strings). Dynamic segments are "*".
 */
export const REGISTERED_QUERY_KEYS = [
  "[\"*\"]",
  "[\"/api/activity\"]",
  "[\"/api/admin/clinic-join-code\"]",
  "[\"/api/admin/cursor-bug-fixer/config\"]",
  "[\"/api/alert-acks\"]",
  "[\"/api/analytics\"]",
  "[\"/api/analytics/readiness-forecast\"]",
  "[\"/api/analytics/shift-completion\",\"*\"]",
  "[\"/api/appointments\",\"*\"]",
  "[\"/api/appointments/meta\",\"*\"]",
  "[\"/api/asset-types\",\"*\",\"conditions\"]",
  "[\"/api/asset-types\"]",
  "[\"/api/audit-logs\",\"*\",\"*\",\"*\",\"*\",\"*\"]",
  "[\"/api/clinical-check-in/me/active\"]",
  "[\"/api/code-blue/history\"]",
  "[\"/api/code-blue/sessions/active\"]",
  "[\"/api/containers\"]",
  "[\"/api/containers/detail\",\"*\"]",
  "[\"/api/crash-cart/checks/latest\"]",
  "[\"/api/crash-cart/items\"]",
  "[\"/api/display/devices\"]",
  "[\"/api/display/snapshot\"]",
  "[\"/api/docking/coordinator\",\"*\"]",
  "[\"/api/docking/coordinator\"]",
  "[\"/api/docking/reconciliation\"]",
  "[\"/api/docking/rooms\",\"*\",\"sweep\"]",
  "[\"/api/docks\"]",
  "[\"/api/equipment\",\"*\"]",
  "[\"/api/equipment\",\"active\"]",
  "[\"/api/equipment\",\"paginated\",\"*\",\"*\",\"*\",\"*\",\"*\",\"*\"]",
  "[\"/api/equipment\",\"paginated\"]",
  "[\"/api/equipment\"]",
  "[\"/api/equipment/*\"]",
  "[\"/api/equipment/*/location-inference\"]",
  "[\"/api/equipment/*/logs\",\"admin\",\"*\"]",
  "[\"/api/equipment/*/logs\"]",
  "[\"/api/equipment/*/transfers\"]",
  "[\"/api/equipment/deleted\"]",
  "[\"/api/equipment/locate\",\"*\"]",
  "[\"/api/equipment/my\"]",
  "[\"/api/equipment/paginated\"]",
  "[\"/api/folders\"]",
  "[\"/api/home/dashboard\"]",
  "[\"/api/inventory-items\"]",
  "[\"/api/nudges\"]",
  "[\"/api/operational-metrics/summary\",\"*\"]",
  "[\"/api/platform/capabilities\"]",
  "[\"/api/procurement\",\"*\"]",
  "[\"/api/procurement\"]",
  "[\"/api/restock/container-items\",\"*\"]",
  "[\"/api/restock/container-items\"]",
  "[\"/api/rooms\",\"*\",\"activity\"]",
  "[\"/api/rooms\",\"*\"]",
  "[\"/api/rooms\"]",
  "[\"/api/shift-adjustments\",\"mine\"]",
  "[\"/api/shift-adjustments\",\"pending\"]",
  "[\"/api/shift-adjustments\"]",
  "[\"/api/shift-chat/archive\",\"*\"]",
  "[\"/api/shift-chat/messages\"]",
  "[\"/api/shift-handover\"]",
  "[\"/api/shifts\"]",
  "[\"/api/shifts/import/shift-names\"]",
  "[\"/api/shifts/imports\"]",
  "[\"/api/support\"]",
  "[\"/api/support/unresolved-count\"]",
  "[\"/api/tasks/recommendations\"]",
  "[\"/api/users\",\"active\"]",
  "[\"/api/users\"]",
  "[\"/api/users/deleted\"]",
  "[\"/api/users/managers\"]",
  "[\"/api/users/me\",\"doctor-gate\"]",
  "[\"/api/users/me\"]",
  "[\"/api/users/me/shift-activity\",\"*\"]",
  "[\"/api/users/pending\"]",
  "[\"condition-states\",\"*\"]",
  "[\"console\",\"audit-log\",\"*\"]",
  "[\"console\",\"equipment-governance\"]",
  "[\"console\",\"integrations\",\"adapters\"]",
  "[\"console\",\"integrations\",\"configs\"]",
  "[\"console\",\"inventory\",\"lowstock\"]",
  "[\"console\",\"inventory\",\"po\"]",
  "[\"console\",\"inventory\",\"restock\"]",
  "[\"console\",\"notifications\"]",
  "[\"console\",\"ops-health\",\"dlq\"]",
  "[\"console\",\"ops-health\",\"health\"]",
  "[\"console\",\"rfid-readers\",\"managed\"]",
  "[\"console\",\"webhooks\"]",
  "[\"cop\",\"orphan-drug-alerts\"]",
  "[\"deployability\",\"*\"]",
  "[\"equipment-rfid\",\"*\"]",
  "[\"equipment-truth\",\"*\"]",
  "[\"equipment-truth\"]",
  "[\"equipment-waitlist\",\"*\"]",
  "[\"inventory-item-detail\",\"*\"]",
  "[\"staging-queue\",\"*\"]",
] as const;

export type RegisteredQueryKey = (typeof REGISTERED_QUERY_KEYS)[number];
