/**
 * TanStack Query key registry (G4 audit baseline).
 *
 * Do not import from application code — this file exists for architecture drift detection only.
 * Regenerate after intentional new keys: pnpm query-keys:audit -- --write-registry
 *
 * @see scripts/architecture/collect-query-keys.mjs
 * @see docs/architecture/architecture-hardening-addendum.md §9.4
 */
export const QUERY_KEY_REGISTRY_VERSION = 1 as const;

/**
 * Normalized query key shapes (JSON array strings). Dynamic segments are "*".
 */
export const REGISTERED_QUERY_KEYS = [
  "[\"/api/activity\",\"patient\",\"*\"]",
  "[\"/api/activity\"]",
  "[\"/api/admin/medication-integrity\"]",
  "[\"/api/admin/outbox-health\"]",
  "[\"/api/admin/outbox/dlq\",\"initial\"]",
  "[\"/api/admin/outbox/dlq\"]",
  "[\"/api/alert-acks\"]",
  "[\"/api/analytics\"]",
  "[\"/api/analytics/shift-completion\",\"*\"]",
  "[\"/api/animals/active\"]",
  "[\"/api/appointments\",\"*\"]",
  "[\"/api/appointments/meta\",\"*\"]",
  "[\"/api/asset-types\",\"*\",\"conditions\"]",
  "[\"/api/asset-types\"]",
  "[\"/api/audit-logs\",\"*\",\"*\",\"*\",\"*\",\"*\"]",
  "[\"/api/billing\",\"*\",\"*\"]",
  "[\"/api/billing\",\"patient\",\"*\"]",
  "[\"/api/billing\"]",
  "[\"/api/billing/inventory-jobs\",\"*\"]",
  "[\"/api/billing/inventory-jobs\"]",
  "[\"/api/billing/leakage-report\",\"*\"]",
  "[\"/api/billing/summary\",\"*\"]",
  "[\"/api/code-blue/history\"]",
  "[\"/api/code-blue/reconciliation\"]",
  "[\"/api/code-blue/sessions\",\"*\",\"dispenses\"]",
  "[\"/api/code-blue/sessions/active\"]",
  "[\"/api/containers\"]",
  "[\"/api/containers/detail\",\"*\"]",
  "[\"/api/crash-cart/checks/latest\"]",
  "[\"/api/crash-cart/items\"]",
  "[\"/api/display/snapshot\"]",
  "[\"/api/docks\"]",
  "[\"/api/equipment\",\"*\"]",
  "[\"/api/equipment\",\"active\"]",
  "[\"/api/equipment\",\"paginated\",\"*\",\"*\",\"*\",\"*\",\"*\",\"*\"]",
  "[\"/api/equipment\",\"paginated\"]",
  "[\"/api/equipment\"]",
  "[\"/api/equipment/*\"]",
  "[\"/api/equipment/*/logs\",\"admin\",\"*\"]",
  "[\"/api/equipment/*/logs\"]",
  "[\"/api/equipment/*/transfers\"]",
  "[\"/api/equipment/deleted\"]",
  "[\"/api/equipment/my\"]",
  "[\"/api/equipment/paginated\"]",
  "[\"/api/equipment/pilot-coverage\"]",
  "[\"/api/folders\"]",
  "[\"/api/home/dashboard\"]",
  "[\"/api/inventory-items\"]",
  "[\"/api/metrics\"]",
  "[\"/api/operational-metrics/summary\",\"*\"]",
  "[\"/api/patients\",\"*\",\"*\"]",
  "[\"/api/patients\",\"active\"]",
  "[\"/api/patients\",\"by-animal\",\"*\"]",
  "[\"/api/patients\"]",
  "[\"/api/pilot/config\"]",
  "[\"/api/procurement\",\"*\"]",
  "[\"/api/procurement\"]",
  "[\"/api/queue/metrics\"]",
  "[\"/api/restock/container-items\",\"*\"]",
  "[\"/api/restock/container-items\"]",
  "[\"/api/rooms\",\"*\",\"activity\"]",
  "[\"/api/rooms\",\"*\"]",
  "[\"/api/rooms\"]",
  "[\"/api/shift-chat/archive\",\"*\"]",
  "[\"/api/shift-chat/messages\"]",
  "[\"/api/shift-handover\"]",
  "[\"/api/shift-handover/discharge\",\"*\"]",
  "[\"/api/shift-handover/patient-handoffs\",\"*\"]",
  "[\"/api/shift-handover/patient-handoffs\"]",
  "[\"/api/shift-handover/patient-handoffs/eligible-patients\"]",
  "[\"/api/shift-handover/patient-handoffs/eligible-staff\"]",
  "[\"/api/shift-handover/patient-handoffs/mine\"]",
  "[\"/api/shift-handover/patients\"]",
  "[\"/api/shift-handover/pending-emergencies\"]",
  "[\"/api/shift-handover/snapshot/latest\"]",
  "[\"/api/shift-handover/summary\"]",
  "[\"/api/shifts\"]",
  "[\"/api/shifts/imports\"]",
  "[\"/api/stability/logs\",\"*\",\"*\"]",
  "[\"/api/stability/logs\"]",
  "[\"/api/stability/results\"]",
  "[\"/api/stability/status\"]",
  "[\"/api/support\"]",
  "[\"/api/support/unresolved-count\"]",
  "[\"/api/tasks/recommendations\"]",
  "[\"/api/users\"]",
  "[\"/api/users/deleted\"]",
  "[\"/api/users/managers\"]",
  "[\"/api/users/me\"]",
  "[\"/api/users/pending\"]",
  "[\"condition-states\",\"*\"]",
  "[\"cop\",\"orphan-drug-alerts\"]",
  "[\"deployability\",\"*\"]",
  "[\"equipment-truth\",\"*\"]",
  "[\"equipment-rfid\",\"*\"]",
  "[\"equipment-waitlist\",\"*\"]",
  "[\"er\",\"admission-state\"]",
  "[\"er\",\"assignees\"]",
  "[\"er\",\"board\"]",
  "[\"er\",\"eligible-hospitalizations\"]",
  "[\"er\",\"impact\",\"*\"]",
  "[\"er\",\"impact-kpis\",\"*\"]",
  "[\"er-board\"]",
  "[\"er-mode-state\"]",
  "[\"staging-queue\",\"*\"]",
] as const;

export type RegisteredQueryKey = (typeof REGISTERED_QUERY_KEYS)[number];
