// Design system entry — exports all visual components for the DS bundle.
// This file is generated by /design-sync and is NOT used by the app itself.

// ── UI primitives (shadcn/radix-ui base) ────────────────────────────
export * from "@/components/ui/alert-dialog";
export * from "@/components/ui/badge";
export * from "@/components/ui/button";
export * from "@/components/ui/card";
export * from "@/components/ui/checkbox";
export * from "@/components/ui/dialog";
export * from "@/components/ui/empty-state";
export * from "@/components/ui/error-card";
export * from "@/components/ui/help-tooltip";
export * from "@/components/ui/input";
export * from "@/components/ui/label";
export * from "@/components/ui/loading-section";
export * from "@/components/ui/section-list";
export * from "@/components/ui/select";
export * from "@/components/ui/sheet";
export * from "@/components/ui/skeleton";
export * from "@/components/ui/skeleton-cards";
export * from "@/components/ui/status-badge";
export * from "@/components/ui/tabs";
export * from "@/components/ui/textarea";
export * from "@/components/ui/app-error-boundary";
export * from "@/components/ui/page-error-boundary";

// ── Layout shell ─────────────────────────────────────────────────────
export { AppShell } from "@/components/layout/AppShell";
export { Breadcrumb } from "@/components/layout/Breadcrumb";
export { IconSidebar } from "@/components/layout/IconSidebar";
export { PageShell } from "@/components/layout/PageShell";
export { Sidebar } from "@/components/layout/Sidebar";
export { Topbar } from "@/components/layout/Topbar";

// ── Alerts ───────────────────────────────────────────────────────────
export * from "@/components/alerts/AlertCard";
export * from "@/components/alerts/AlertsProView";
export * from "@/components/alerts-dropdown";

// ── Equipment ────────────────────────────────────────────────────────
export * from "@/components/equipment/DeployabilityBadge";
export * from "@/components/equipment/EquipmentDetailStatusStrip";
export * from "@/components/equipment/EquipmentTruthCard";
export * from "@/components/equipment/ReservationBanner";
export * from "@/components/equipment/ConditionChecklist";
export * from "@/components/equipment/HolderReturnContext";
export * from "@/components/equipment/EquipmentTriageList";
export * from "@/components/equipment/EquipmentHeroCoverageStrip";
export * from "@/components/equipment/StagingQueuePanel";
export * from "@/components/equipment/WaitlistPanel";
export * from "@/components/equipment/OperationalMetricsDashboard";
export * from "@/components/equipment/AssetCopilotPanel";
export * from "@/components/equipment/EquipmentConfirmInRoomSheet";
export * from "@/components/equipment/EquipmentDetailActivityTab";
export * from "@/components/equipment/EquipmentDetailToolsSheet";
export * from "@/components/equipment/EquipmentRoomSweepSheet";
export * from "@/components/equipment/DockReturnFlow";

// ── Home ─────────────────────────────────────────────────────────────
export * from "@/components/home/ShiftProgressHero";

// ── Skeletons ────────────────────────────────────────────────────────
export * from "@/components/skeletons/equipment-detail-skeleton";
export * from "@/components/skeletons/equipment-list-skeleton";

// ── Shared app components ─────────────────────────────────────────────
export * from "@/components/sw-update-banner";
export * from "@/components/sync-status-banner";
export * from "@/components/update-banner";
export * from "@/components/route-fallback";
export * from "@/components/settings-controls";
export * from "@/components/first-scan-celebration";
export * from "@/components/shift-summary-sheet";
export * from "@/components/move-room-sheet";
export * from "@/components/report-issue-dialog";
export * from "@/components/return-plug-dialog";
export * from "@/components/crash-cart-admin-sheet";
export * from "@/components/csv-import-dialog";
export * from "@/components/sync-queue-sheet";
export * from "@/components/onboarding-walkthrough";
export * from "@/components/VirtualizedEquipmentList";
