// Shared dashboard data — English + Hebrew. Each variant consumes this.
const DASH_DATA = {
  en: {
    dir: "ltr",
    greetingKicker: "TODAY · DAY SHIFT",
    greetingName: "Good morning, Liat",
    greetingMeta: "ICU + OR · 4 rooms active · 08:12",
    shiftLabel: "Captured this shift",
    shiftValue: "₪4,820",
    shiftMeta: "23 items billed · 14% above day-shift median",
    kpis: [
      { label: "Active patients",   value: "18",     sub: "In active treatment", icon: "users" },
      { label: "Tasks due",         value: "12",     sub: "Today + overdue",     icon: "listTodo" },
      { label: "Inventory alerts",  value: "3",      sub: "Need review",         icon: "shieldAlert" },
      { label: "Devices healthy",   value: "42 / 47", sub: "89% uptime",         icon: "checkCircle" },
    ],
    actions: [
      { id: "scan", label: "Scan",      hint: "QR or NFC",        icon: "scan",    primary: true },
      { id: "task", label: "Add task",  hint: "Create or assign", icon: "filePlus" },
      { id: "inv",  label: "Inventory", hint: "Stock & assets",   icon: "boxes" },
      { id: "bill", label: "Billing",   hint: "Ledger & charges", icon: "receipt" },
    ],
    activityTitle: "Live activity",
    activityCount: "4 events",
    activity: [
      { name: "ECG monitor · EQ-0492",       action: "Checked out by L. Cohen",    when: "2m",  status: "ok"      },
      { name: "Defibrillator · EQ-0214",     action: "Marked review needed",        when: "12m", status: "issue"   },
      { name: "Syringe pump · EQ-0173",      action: "Returned to ICU 2",          when: "26m", status: "ok"      },
      { name: "Anesthesia ventilator · A-3", action: "Sterilization cycle started", when: "41m", status: "sterilized" },
    ],
    alertsTitle: "Inventory alerts",
    alertsViewAll: "View all",
    alerts: [
      { name: "Defibrillator · EQ-0214",   detail: "Last check 9 days ago — overdue",       tone: "issue" },
      { name: "Syringe pump · EQ-0098",    detail: "Scheduled maintenance · today 16:00",   tone: "maintenance" },
      { name: "Endoscope set",             detail: "Sterilization · 22 min remaining",      tone: "sterilized" },
    ],
    patientsTitle: "Active patients",
    patients: [
      { name: "Bella",   species: "Labrador · 4y",        room: "ICU 1", status: "critical" },
      { name: "Mochi",   species: "British Shorthair · 9y", room: "ICU 2", status: "stable" },
      { name: "Rocco",   species: "Husky · 6y",            room: "OR 3",  status: "post-op" },
    ],
    nav: ["Home", "Patients", "", "Tasks", "More"],
    statusLabel: { ok: "OK", issue: "Issue", maintenance: "Maint", sterilized: "Steril", critical: "Critical", stable: "Stable", "post-op": "Post-op" },
  },
  he: {
    dir: "rtl",
    greetingKicker: "היום · משמרת בוקר",
    greetingName: "בוקר טוב, ליאת",
    greetingMeta: "טיפול נמרץ + חדר ניתוח · 4 חדרים פעילים · 08:12",
    shiftLabel: "נרשם במשמרת זו",
    shiftValue: "₪4,820",
    shiftMeta: "23 פריטים חויבו · 14% מעל החציון",
    kpis: [
      { label: "מטופלים פעילים",  value: "18",      sub: "בטיפול פעיל",       icon: "users" },
      { label: "משימות לביצוע",   value: "12",      sub: "היום + באיחור",     icon: "listTodo" },
      { label: "התראות מלאי",     value: "3",       sub: "דורש בדיקה",        icon: "shieldAlert" },
      { label: "ציוד תקין",       value: "42 / 47", sub: "89% זמינות",        icon: "checkCircle" },
    ],
    actions: [
      { id: "scan", label: "סריקה",     hint: "QR או NFC",         icon: "scan",    primary: true },
      { id: "task", label: "הוסף משימה", hint: "צור או שייך",       icon: "filePlus" },
      { id: "inv",  label: "מלאי",       hint: "מלאי ונכסים",      icon: "boxes" },
      { id: "bill", label: "חיובים",    hint: "פנקס וחיובים",      icon: "receipt" },
    ],
    activityTitle: "פעילות חיה",
    activityCount: "4 אירועים",
    activity: [
      { name: "מוניטור ECG · EQ-0492",  action: "נלקח ע״י ל. כהן",       when: "2 ד׳",  status: "ok" },
      { name: "דפיברילטור · EQ-0214",   action: "סומן לבדיקה",            when: "12 ד׳", status: "issue" },
      { name: "משאבת מזרק · EQ-0173",   action: "הוחזר לטנ״צ 2",          when: "26 ד׳", status: "ok" },
      { name: "מכונת הרדמה · A-3",      action: "מחזור עיקור החל",        when: "41 ד׳", status: "sterilized" },
    ],
    alertsTitle: "התראות מלאי",
    alertsViewAll: "כל ההתראות",
    alerts: [
      { name: "דפיברילטור · EQ-0214", detail: "נבדק לפני 9 ימים — באיחור",      tone: "issue" },
      { name: "משאבת מזרק · EQ-0098",  detail: "תחזוקה מתוכננת · היום 16:00",   tone: "maintenance" },
      { name: "סט אנדוסקופ",            detail: "עיקור · 22 דקות נותרו",        tone: "sterilized" },
    ],
    patientsTitle: "מטופלים פעילים",
    patients: [
      { name: "בלה",   species: "לברדור · בת 4",       room: "טנ״צ 1", status: "critical" },
      { name: "מוצ׳י", species: "בריטי קצר־שיער · בן 9", room: "טנ״צ 2", status: "stable" },
      { name: "רוקו",  species: "האסקי · בן 6",         room: "ני׳ 3",   status: "post-op" },
    ],
    nav: ["בית", "מטופלים", "", "משימות", "עוד"],
    statusLabel: { ok: "תקין", issue: "תקלה", maintenance: "תחזוקה", sterilized: "עיקור", critical: "קריטי", stable: "יציב", "post-op": "אחרי ניתוח" },
  },
};
window.DASH_DATA = DASH_DATA;
